wiki_links/lib/wiki_links_web/router.ex
defmodule WikiLinksWeb.Router do
  use WikiLinksWeb, :router

  import WikiLinksWeb.UserAuth

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {WikiLinksWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_current_user
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", WikiLinksWeb do
    pipe_through :browser

    get "/", PageController, :index
    resources "/links", LinkController
    get "/fav_link", FavLinkController, :index
    get "/update_fav_link/:id", LinkController, :updatefav
    get "/links/delete/:id", LinkController, :deletelink
    get "/generate/fav_pdf",FavLinkController, :pdf
    get "/generate/link_pdf",LinkController, :link_pdf
  end

  # Other scopes may use custom stacks.
  # scope "/api", WikiLinksWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser

      live_dashboard "/dashboard", metrics: WikiLinksWeb.Telemetry
    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end

  ## Authentication routes

  scope "/", WikiLinksWeb do
    pipe_through [:browser, :redirect_if_user_is_authenticated]

    get "/users/register", UserRegistrationController, :new
    post "/users/register", UserRegistrationController, :create
    get "/users/log_in", UserSessionController, :new
    post "/users/log_in", UserSessionController, :create
    get "/users/reset_password", UserResetPasswordController, :new
    post "/users/reset_password", UserResetPasswordController, :create
    get "/users/reset_password/:token", UserResetPasswordController, :edit
    put "/users/reset_password/:token", UserResetPasswordController, :update
  end

  scope "/", WikiLinksWeb do
    pipe_through [:browser, :require_authenticated_user]

    get "/users/settings", UserSettingsController, :edit
    put "/users/settings", UserSettingsController, :update
    get "/users/settings/confirm_email/:token", UserSettingsController, :confirm_email
  end

  scope "/", WikiLinksWeb do
    pipe_through [:browser]

    get "/users/log_out", UserSessionController, :delete
    get "/users/confirm", UserConfirmationController, :new
    post "/users/confirm", UserConfirmationController, :create
    get "/users/confirm/:token", UserConfirmationController, :edit
    post "/users/confirm/:token", UserConfirmationController, :update
  end
end

wiki_links/lib/wiki_links/wiki_link/link.ex
defmodule WikiLinks.Wiki_link.Link do
  use Ecto.Schema
  import Ecto.Changeset
  import Ecto.Query


  schema "links" do
    field :description, :string
    field :fav, :boolean, default: false
    field :link, :string
    field :tag, :string

    timestamps()
  end

  @doc false
  def changeset(link, attrs) do
    link
    |> cast(attrs, [:link, :tag, :description, :fav])
    |> validate_required([:link, :tag, :description, :fav])
  end

  def search(query, search_term) do
    wildcard_search = "%#{search_term}%"
query
  |> where([link], ilike(link.link, ^wildcard_search))


  end

  def search_tag(query, search_tag) do
    wildcard_search_tag = "%#{search_tag}%"
    from link in query,
    where: ilike(link.tag, ^wildcard_search_tag)
  end

  def search_link_tag(query,search_tag,search_link) do
    wildcard_tag = "%#{search_tag}%"
    wildcard_link = "%#{search_link}%"
query
   |> where([link],ilike(link.tag, ^wildcard_tag))
   |> where([link],ilike(link.link, ^wildcard_link))
  end
end

wiki_links/lib/wiki_links_web/controllers/link_controller.ex
defmodule WikiLinksWeb.LinkController do
  use WikiLinksWeb, :controller
  alias WikiLinks.GeneratePdf.Pdf
  alias WikiLinks.Wiki_link
  alias WikiLinks.Wiki_link.Link

  @doc """
  filter the links when searched by Link Tag only
  """
  def index(conn, %{"query_tag" => query_tag,"query" => query}) when query_tag != ""  and query == "" do
    links= Wiki_link.list_tag(query_tag)
    render(conn, "index.html", links: links)
end
 @doc """
  filter the links when searched by Link  only
  """
def index(conn, %{"query_tag" => query_tag,"query" => query}) when query_tag == ""  and query != "" do
  links= Wiki_link.list_links(query)
  render(conn, "index.html", links: links)
end

 @doc """
  filter the links when searched by Link  and  Link Tag both
  """
def index(conn, %{"query_tag" => query_tag, "query" => query}) when query_tag != "" and query != "" do
  links= Wiki_link.link_tag(query_tag,query)
  render(conn, "index.html", links: links)
end
 @doc """
 show all saved Links
  """
def index(conn, _params) do
  links = Wiki_link.show_links()
  render(conn, "index.html", links: links)
  end

  def new(conn, _params) do
    changeset = Wiki_link.change_link(%Link{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"link" => link_params}) do
    case Wiki_link.create_link(link_params) do
      {:ok, link} ->
        conn
        |> put_flash(:info, "Link created successfully.")
        |> redirect(to: Routes.link_path(conn, :show, link))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    link = Wiki_link.get_link!(id)
    render(conn, "show.html", link: link)
  end

  def edit(conn, %{"id" => id}) do
    link = Wiki_link.get_link!(id)
    changeset = Wiki_link.change_link(link)
    render(conn, "edit.html", link: link, changeset: changeset)
  end

  def update(conn, %{"id" => id, "link" => link_params}) do
    link = Wiki_link.get_link!(id)

    case Wiki_link.update_link(link, link_params) do
      {:ok, link} ->
        conn
        |> put_flash(:info, "Link updated successfully.")
        |> redirect(to: Routes.link_path(conn, :show, link))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", link: link, changeset: changeset)
    end
  end

  def deletelink(conn, %{"id" => id}) do
    link = Wiki_link.get_link!(id)
    {:ok, _link} = Wiki_link.delete_link(link)

    conn
    |> put_flash(:info, "Link deleted successfully.")
    |> redirect(to: Routes.link_path(conn, :index))
  end


 @doc """
  mark  or unmark the link favourate
  """
  def updatefav(conn, %{"id" => id}) do
    link = Wiki_link.get_link!(id)
    fav_link = link.fav
    if link.fav == true do
      Wiki_link.fav_update(id)
      conn
    |> put_flash(:info, " UnMarked faviourate ")
    |> redirect(to: Routes.link_path(conn, :index))
    else
      Wiki_link.unfav_update(id)
    end
    conn
    |> put_flash(:info, "Marked faviourate")
    |> redirect(to: Routes.link_path(conn, :index))
  end

 @doc """
  generate the pdf for links through GenServer
  """
  def link_pdf(conn, _params) do
    links = Wiki_link.show_links()
    html = Phoenix.View.render_to_string(WikiLinksWeb.LinkView,"pdf.html", links: links)
    case Pdf.generate_pdf(html)
    |> IO.inspect(label: "File Name")
     do
       {:ok, filename} ->
        {:ok, pdf_content} = File.read(filename)
         IO.inspect(filename, label: " 2nd file name")
         conn
            |> put_resp_content_type("application/pdf")
            |> put_resp_header("content-disposition", "attachment;filename=#{filename}")
            |> send_resp(200, pdf_content)
    end
  end
end

wiki_links/lib/wiki_links_web/views/link_view.ex
defmodule WikiLinksWeb.LinkView do
  use WikiLinksWeb, :view
end

wiki_links/lib/wiki_links_web/templates/link/edit.html.heex
<h1>Edit Link</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.link_path(@conn, :update, @link)) %>

<span><%= link "Back", to: Routes.link_path(@conn, :index) %></span>

wiki_links/lib/wiki_links_web/templates/link/form.html.heex
<.form let={f} for={@changeset} action={@action}>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <%= label f, :link %>
  <%= text_input f, :link %>
  <%= error_tag f, :link %>

  <%= label f, :tag %>
  <%= text_input f, :tag %>
  <%= error_tag f, :tag %>

  <%= label f, :description %>
  <%= text_input f, :description %>
  <%= error_tag f, :description %>

  <%= label f, :fav %>
  <%= checkbox f, :fav %>
  <%= error_tag f, :fav %>

  <div>
    <%= submit "Save" %>
  </div>
</.form>

wiki_links/lib/wiki_links_web/templates/link/index.html.heex
<h1>Listing Links</h1>
<%= form_for @conn, Routes.link_path(@conn, :index), [method: :get], fn f -> %>
      <%= search_input f, :query, placeholder: "search by link" %>
       <%= search_input f, :query_tag, placeholder: "search by tag" %>
      <%= submit "Search" %>
<% end %>
<table>
  <thead>
    <tr>
      <th>Link</th>
      <th>Tag</th>
      <th>Description</th>
      

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for link <- @links do %>
    <tr>
      <td><%= link.link %></td>
      <td><%= link.tag %></td>
      <td><%= link.description %></td>
<%= if @current_user do %>
      <td>
      <%= if link.fav == true do %>
        <span><%= link "Mark Unfav", to: Routes.link_path(@conn, :updatefav,  link) %></span> |
         <% else %>
          <span><%= link "Mark fav", to: Routes.link_path(@conn, :updatefav,  link) %></span> |
          <% end %>
         <span><%= link "Show", to: Routes.link_path(@conn, :show, link) %></span> |
        <span><%= link "Edit", to: Routes.link_path(@conn, :edit, link) %></span> |
        <span><%= link "Delete", to: Routes.link_path(@conn, :deletelink, link)%></span>
      </td>
     <% else %>
     <td>
        <span><%= link "Show", to: Routes.link_path(@conn, :show, link) %></span>
      </td>
      <% end %>
    </tr>
<% end %>
  </tbody>
</table>
<%= if @current_user do %>
<span><%= link "New Link", to: Routes.link_path(@conn, :new) %></span> | 
<span><%= link "Fav Link", to: Routes.fav_link_path(@conn, :index) %></span> | 
<span><%= link "Generate PDF", to: Routes.link_path(@conn, :link_pdf) %></span>
<% end %>

wiki_links/lib/wiki_links_web/templates/link/new.html.heex
<h1>New Link</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.link_path(@conn, :create)) %>

<span><%= link "Back", to: Routes.link_path(@conn, :index) %></span>

wiki_links/lib/wiki_links_web/templates/link/pdf.html.heex
<h1>Listing  Links</h1>
<table>
  <thead>
    <tr>
      <th>Link</th>
      <td></td>
      <th>Tag</th>
      <td></td>
      <th>Description</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for link <- @links do %>
    <tr>
      <td><%= link.link %></td>
      <td></td>
      <td><%= link.tag %></td>
      <td></td>
      <td><%= link.description %></td>
      <td></td>
      </tr>
    <% end %>
  </tbody>
</table>

wiki_links/lib/wiki_links_web/templates/link/show.html.heex
<h1>Show Link</h1>

<ul>

  <li>
    <strong>Link:</strong>
    <%= @link.link %>
  </li>

  <li>
    <strong>Tag:</strong>
    <%= @link.tag %>
  </li>

  <li>
    <strong>Description:</strong>
    <%= @link.description %>
  </li>

  <li>
    <strong>Fav:</strong>
    <%= @link.fav %>
  </li>

</ul>
<%= if @current_user do %>
<span><%= link "Edit", to: Routes.link_path(@conn, :edit, @link) %></span> |
<span><%= link "Back", to: Routes.link_path(@conn, :index) %></span>
<% else %>
<span><%= link "Back", to: Routes.link_path(@conn, :index) %></span>
<% end %>